Various and sundry fixes for Thrust's CPP backends. (#1722)
* Fix non-CUDA Thrust handling of __host__/__device__

* Add some missing headers in the Thrust CPU backends.

* Remove unused variables.

* Add missing header.

* Move deprecation markup to `result_of` definition.

Having the deprecation markup on the declaration instead of the definition cause the deprecation diagnostics to be emitted when defining the deprecate type on gcc.
Moving the markup fixes this.

* Don't expose builtins as functions in thrust.

error: use of built-in trait '__is_same(..., ...)' in function signature; use library traits instead.

* Remove re-declaration of `reference_wrapper`

This type was already forward-declared in `is_reference_wrapper.h`.
Redeclaring it with the vis attribute broke gcc.

* Disable failing OpenMP test (tracked in #1715).

* Print CMake configure step on windows.

* Use installed TBB CMake configs if available.

Fallback to our FindTBB.cmake as a last resort.