hipblaslt/clients: Include and link cblas.
This patch fixes the clients build with the netlib / LAPACK
as well as the OpenBLAS implementations of BLAS.

Enabling clients by setting `HIPBLASLT_ENABLE_CLIENT` results in
linking errors due to cblas not being implicitly linked when calling
find_package(LAPACK):
```
ld.lld: error: undefined symbol: cblas_sgemm
ld.lld: error: undefined symbol: cblas_dgemm
```

Since CMake only ships internal modules to find the fortran
implementation of BLAS, this patch resolves this by using
pkgconfig to retrieve and explicitly link the cblas library
which exposes the above symbols.

In addition this patch adds the cblas include directories to the
hipblaslt-clients-common target, which fixes the build with OpenBLAS
and other BLAS implementation that put cblas.h into a different path
than netlib.

Fixes the following build issue when building with OpenBLAS:
```
clients/common/include/allclose.hpp:30:10: fatal error: 'cblas.h' file not found
   30 | #include "cblas.h"
      |          ^~~~~~~~~
```

Signed-off-by: Lubosz Sarnecki <lubosz@gmail.com>