docs(hipfft): enable generating llms.txt and fix Doxygen errors (#12030)
## Motivation

- Enable generating llms.txt and llms-full.txt (see https://llmstxt.org)
for LLM-assisted access.

- Fix Doxygen errors.

<!-- Explain the purpose of this PR and the goals it aims to achieve.
-->

## Technical Details

- Add `rocm_docs_generate_llms = True` in the Sphinx config

- Also, fix Doxygen errors preventing the docs from building

  - Remove non-existant README from Doxyfile config

    ```bash
    error: Specified markdown mainpage '../README.md' does not exist
     (warning treated as error, aborting now)
    Exiting...

    Extension error (rocm_docs.doxygen):
Handler <function _run_doxygen at 0x79776bf00a60> for event
'config-inited' threw an exception (exception: Failed when running
doxygen)
    ```

- Expand HIPFFT_DEPRECATED_MSG(x) to nothing via PREDEFINED, so the
macro disappears before parsing and the `@param` tags in the doc comment
correctly associate with the actual function declaration below.

   ```bash

/home/petepark/amd/rocm-libraries/projects/hipfft/library/include/hipfft/hipfftXt.h:113:
error: argument 'plan' of command @param is not found in the argument
list of HIPFFT_DEPRECATED_MSG("Function pointer callbacks are
deprecated; use hipfftXtSetJITCallback for JIT callbacks.") (warning
treated as error, aborting now)
   Exiting...

   Extension error (rocm_docs.doxygen):
Handler <function _run_doxygen at 0x74d7ae1f4a60> for event
'config-inited' threw an exception (exception: Failed when running
doxygen)
   ```

<!-- Explain the changes along with any relevant GitHub links. -->

## Issue Tracking

ISSUE ID: AIROCDOC-4235

<!-- Include a GitHub Issue and/or JIRA ID. Do not post any full JIRA
links here. -->
<!-- GitHub issue: https://github.com/ROCm/rocm-systems/issues/1234 -->
<!-- JIRA ID: EXAMPLECOMPONENT-1234 -->

## Test Plan

<!-- Explain any relevant testing done to verify this PR. -->

Look at
-
[llms.txt](https://rocm.docs.amd.com/projects/hipFFT/en/users-peterjunpark-hipfft-llmstxt/llms.txt)
-
[llms-full.txt](https://rocm.docs.amd.com/projects/hipFFT/en/users-peterjunpark-hipfft-llmstxt/llms-full.txt)
## Test Result

<!-- Briefly summarize test outcomes. -->

Looks ok. Passes Chrome's Lighthouse audit for agentic browsing:
  
<img width="1472" height="1230" alt="image"
src="https://github.com/user-attachments/assets/54e7d2e8-6b98-45c2-91d9-fdd0d322375b"
/>


## Submission Checklist

- [x] Look over the contributing guidelines at
https://github.com/ROCm/rocm-systems/blob/develop/CONTRIBUTING.md.