[rocThrust] Fix benchmark build on Windows (#5953)
## Motivation

Currently the rocThrust benchmark fails to build on Windows because
googlebench enables `-Werror` and also throws the following warning with
clang on Windows:

`In file included from
build-wasm/_deps/benchmark-src/src/benchmark_register.cc:39:
build-wasm/_deps/benchmark-src/include/benchmark/benchmark.h:1461:30:
error: '__COUNTER__' is a C2y extension [-Werror,-Wc2y-extensions]
1461 | #if defined(__COUNTER__) && (__COUNTER__ + 1 == __COUNTER__ + 0)`

The warning has been suppressed in
[googlebench](https://github.com/google/benchmark/issues/2057) and is
available in v1.9.5. I have bumped to 1.9.5, however it seems to cause
several more, different warnings as error problem. For the time being I
will suppress those warnings on Windows only until they are addressed in
googlebench in a future relase.

## Technical Details

Update googlebench from 1.9.4 to 1.9.5, and suppress two warnings for
googlebench.

## Test Plan

Rebuilt benchmarks.

## Test Result

Build passes.

## Submission Checklist

- [ ] Look over the contributing guidelines at
https://github.com/ROCm/ROCm/blob/develop/CONTRIBUTING.md#pull-requests.