docs(hipsparse): fix documentation warnings (#10578)
## Motivation

The documentation warnings:

```
/src/rocm-libraries/projects/hipsparse/docs/reference/generic.rst:346: WARNING: doxygenfunction: Cannot find function "hipsparseSpGEAM_createDescr" in doxygen xml output for project "hipsparse" from directory: doxygen/xml [docutils]
/src/rocm-libraries/projects/hipsparse/docs/reference/generic.rst:351: WARNING: doxygenfunction: Cannot find function "hipsparseSpGEAM_destroyDescr" in doxygen xml output for project "hipsparse" from directory: doxygen/xml [docutils]
/src/rocm-libraries/projects/hipsparse/docs/reference/generic.rst:356: WARNING: doxygenfunction: Cannot find function "hipsparseSpGEAM_bufferSize" in doxygen xml output for project "hipsparse" from directory: doxygen/xml [docutils]
/src/rocm-libraries/projects/hipsparse/docs/reference/generic.rst:361: WARNING: doxygenfunction: Cannot find function "hipsparseSpGEAM_nnz" in doxygen xml output for project "hipsparse" from directory: doxygen/xml [docutils]
/src/rocm-libraries/projects/hipsparse/docs/reference/generic.rst:366: WARNING: doxygenfunction: Cannot find function "hipsparseSpGEAM" in doxygen xml output for project "hipsparse" from directory: doxygen/xml [docutils]
/src/rocm-libraries/projects/hipsparse/docs/reference/types.rst:118: WARNING: doxygentypedef: Cannot find typedef "hipsparseSpGEAMDescr_t" in doxygen xml output for project "hipsparse" from directory: doxygen/xml [docutils]
/src/rocm-libraries/projects/hipsparse/docs/reference/types.rst:265: WARNING: doxygenenum: Cannot find enum "hipsparseSpGEAMAlg_t" in doxygen xml output for project "hipsparse" from directory: doxygen/xml [docutils]
```

started appearing after https://github.com/ROCm/rocm-libraries/pull/9648
was merged. When warnings are treated like errors this causes the
documentation builds to fail. This PR fixes these warnings.